environments:
  dev:
    values:
      - environment-values/dev.yaml
  prod:
    values:
      - environment-values/prod.yaml
---
repositories:
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: external-secrets
    namespace: external-secrets-operator
    chart: external-secrets/external-secrets
    version: "2.3.0"
    createNamespace: true
    wait: true
    values:
      - helm/external-secrets-operator/values.yaml.gotmpl

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: "v1.20.2"
    createNamespace: true
    wait: true
    needs:
      - external-secrets-operator/external-secrets
    values:
      - helm/cert-manager/values.yaml

  - name: prometheus-crds
    namespace: monitoring
    chart: prometheus-community/prometheus-operator-crds
    version: "28.0.1"
    createNamespace: true

  - name: external-secrets-config
    namespace: external-secrets-operator
    chart: helm/external-secrets-operator/secret-store
    wait: true
    needs:
      - external-secrets-operator/external-secrets
      - cert-manager/cert-manager
      - monitoring/prometheus-crds
    values:
      - helm/external-secrets-operator/secret-store/project-id.yaml.gotmpl
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "helm/cert-manager/cluster-issuer.yaml"
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "wait"
          - "--for=condition=Ready"
          - "clustersecretstore/gcp-secret-manager"
          - "--timeout=60s"

  - name: cert-manager-secrets
    namespace: cert-manager
    chart: helm/cert-manager/secrets
    wait: true
    needs:
      - external-secrets-operator/external-secrets-config
      - cert-manager/cert-manager

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.15.1"
    createNamespace: true
    wait: true
    needs:
      - external-secrets-operator/external-secrets-config
      - monitoring/prometheus-crds
    values:
      - helm/ingress-nginx/values.yaml.gotmpl

  - name: argocd-secrets
    namespace: argocd
    chart: helm/argocd/secrets
    createNamespace: true
    wait: true
    needs:
      - external-secrets-operator/external-secrets-config
    values:
      - helm/argocd/secrets/environment-values.yaml.gotmpl

  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: "9.5.4"
    wait: true
    needs:
      - argocd/argocd-secrets
      - ingress-nginx/ingress-nginx
      - cert-manager/cert-manager
    values:
      - helm/argocd/values.yaml.gotmpl

  - name: argocd-bootstrap
    namespace: argocd
    chart: helm/argocd/bootstrap
    wait: true
    needs:
      - argocd/argocd-secrets
      - argocd/argocd
    values:
      - helm/argocd/bootstrap/repo.yaml.gotmpl
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args:
          - "wait"
          - "--for=condition=Established"
          - "crd/applications.argoproj.io"
          - "--timeout=60s"
