controller:
  nodeSelector:
    purpose: infra
  tolerations:
    - key: purpose
      value: infra
      effect: NoSchedule
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  service:
    enabled: true
    type: LoadBalancer

    annotations:
      cloud.google.com/l4-rbs: "enabled"

    loadBalancerIP: "34.118.115.97"

  ingressClassResource:
    name: nginx
    enabled: true
    default: true

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"

    proxy-connect-timeout: "10"
    proxy-read-timeout: "120"
    proxy-send-timeout: "120"

    proxy-body-size: "16m"

    use-gzip: "true"
    gzip-types: "application/json application/javascript text/css text/plain application/xml"

    ssl-redirect: "true"
    hsts: "true"
    hsts-max-age: "31536000"
    hsts-include-subdomains: "true"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

  minAvailable: 1

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/component: controller

defaultBackend:
  enabled: false
