installCRDs: true

nameOverride: external-secrets-operator
fullnameOverride: external-secrets-operator

serviceAccount:
  name: external-secrets-operator
  annotations:
    iam.gke.io/gcp-service-account: dev-external-secrets-operator@platform-dev-e7b0024c.iam.gserviceaccount.com

nodeSelector:
  purpose: infra
tolerations:
  - key: purpose
    value: infra
    effect: NoSchedule

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

webhook:
  nodeSelector:
    purpose: infra
  tolerations:
    - key: purpose
      value: infra
      effect: NoSchedule

certController:
  nodeSelector:
    purpose: infra
  tolerations:
    - key: purpose
      value: infra
      effect: NoSchedule
