env: prod
project_id: platform-prod-813738c6
repo_url: https://github.com/Verggy/gcp-k8s-platform
ingress_ip: "34.118.108.71"
grafana_host: grafana.terraform-portfolio.cloud
shop_host: shop.terraform-portfolio.cloud
argocd_host: argocd.terraform-portfolio.cloud
