apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-secrets
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: grafana-secrets
    spec:
      project: default
      source:
        repoURL: "{{metadata.annotations.repo_url}}"
        targetRevision: main
        path: helm/grafana/secrets
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
