env: dev
project_id: <project_id>
repo_url: https://github.com/<owner>/<repo_name>
ingress_ip: "x.x.x.x"
grafana_host: dev-grafana.<domain>
shop_host: dev-shop.<domain>
argocd_host: dev-argocd.<domain>
acme_email: <email>
