env: prod
project_id: <project_id>
repo_url: https://github.com/<owner>/<repo_name>
ingress_ip: "x.x.x.x"
grafana_host: grafana.<domain>
shop_host: shop.<domain>
argocd_host: argocd.<domain>
acme_email: <email>
