apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
    - secretKey: admin.password
      remoteRef:
        key: argocd-admin
        property: password-hash
    - secretKey: server.secretkey
      remoteRef:
        key: argocd-admin
        property: server-key
